apiVersion: v1
kind: Service
metadata:
  name: echo-service
  labels:
    app: echo-service
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30000
      protocol: TCP
  selector:
    app: echo